# Travis CI build file for SwiftJWT.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.3
      sudo: required
      env: SWIFT_SNAPSHOT=4.1

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
- ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
